import { GeneratedProjectSuite, StudentProfile } from '../types/index';

export function generateUniversitySynopsisMarkdown(
  suite: GeneratedProjectSuite,
  profile: StudentProfile
): string {
  const project = suite.recommendedProjects[suite.selectedProjectIndex] || suite.recommendedProjects[0];
  const blueprint = suite.projectBlueprint;
  const tech = suite.technologyStack;

  return `# UNIVERSITY FINAL-YEAR PROJECT SYNOPSIS
## ${project.title.toUpperCase()}
**Academic Track**: ${profile.branch}  
**Primary Domain**: ${project.category}  
**Proposed Timeline**: ${project.estimatedDuration}  
**Prepared with**: ProjectMentor AI (PromptWars x Parul University)  
**Date**: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}

---

### 1. ABSTRACT & EXECUTIVE SUMMARY
${blueprint.summary}

### 2. PROBLEM STATEMENT
${project.problemStatement}

### 3. TARGET BENEFICIARIES & PERSONAS
${blueprint.userPersonas
  .map(p => `- **${p.role}**: *Problem*: ${p.painPoint} -> *Solution*: ${p.solution}`)
  .join('\n')}

### 4. SYSTEM WORKFLOW & ARCHITECTURAL PIPELINE
${blueprint.systemWorkflow
  .map(w => `${w.step}. **${w.title}**: ${w.description}`)
  .join('\n')}

### 5. CORE MODULES SPECIFICATION
${blueprint.coreModules
  .map(m => `#### Module: ${m.name} (${m.complexity} Complexity)
- **Description**: ${m.description}
- **Inputs**: ${m.inputs}
- **Outputs**: ${m.outputs}`)
  .join('\n\n')}

### 6. HARDWARE & SOFTWARE REQUIREMENTS
- **User Interface / Client**: ${tech.frontend.name} (${tech.frontend.reason})
- **Application Engine / Backend**: ${tech.backend.name} (${tech.backend.reason})
- **AI / Computation Layer**: ${tech.aiLayer.name}
- **Database & Storage**: ${tech.database.name}
- **Deployment Platform**: ${tech.deployment.name}
- **Developer Tools**: ${tech.devTools.join(', ')}
- **Testing Frameworks**: ${tech.testingTools.join(', ')}

### 7. VERIFIED DATASETS & EXTERNAL APIS
- **Datasets**: ${blueprint.suggestedDatasets.map(d => `${d.name} (${d.source})`).join('; ')}
- **External Interfaces**: ${tech.externalApis.map(a => a.name).join(', ')}

### 8. DEVELOPMENT MILESTONES & ROADMAP
| Week / Milestone | Phase Objective | Key Deliverables | Estimated Hours |
|---|---|---|---|
${suite.developmentRoadmap
  .map(m => `| Week ${m.week} | ${m.phaseName} | ${m.deliverables[0]} | ${m.estimatedHours} hrs |`)
  .join('\n')}

### 9. PRE-DEVELOPMENT RISK MITIGATION MATRIX
| Anticipated Engineering Risk | Severity | Mitigation Strategy |
|---|---|---|
${suite.mentorReview.risks
  .map(r => `| ${r.risk} | ${r.severity} | ${r.mitigation} |`)
  .join('\n')}

### 10. VIVA DEFENSE PREPARATION (EXAMINER CURVEBALLS)
${suite.mentorReview.vivaQuestions
  .map((v, i) => `#### Question ${i + 1}: "${v.question}"
- **Defense Strategy**: ${v.answerGuidance}`)
  .join('\n\n')}

---
*Generated by ProjectMentor AI — Empowering Engineering Students with Actionable Blueprints.*
`;
}

export function downloadFile(content: string, filename: string, mimeType: string = 'text/markdown') {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
